using Terraria.ID;
using Terraria.ModLoader;

namespace Ichthyology.Systems
{
    [ReinitializeDuringResizeArrays]
    public static class FishIDSets
    {
        public static bool[] SpaceSC = NPCID.Sets.Factory.CreateNamedSet("SpaceSeaCreatures").Description("Enemies in this set can be caught when fishing in the Space Biome.").RegisterBoolSet(false,
            NPCID.WyvernHead,
            NPCID.WyvernBody,
            NPCID.WyvernBody2,
            NPCID.WyvernBody3,
            NPCID.WyvernTail,
            NPCID.WyvernLegs,
            NPCID.FlyingFish
            //Custom Enemy goes here
            );

        public static bool[] ForestSC = NPCID.Sets.Factory.CreateNamedSet("ForestSeaCreatures").Description("Enemies in this set can be caught when fishing in the Forest Biome").RegisterBoolSet(false,
            NPCID.Zombie,
            NPCID.DemonEye,
            NPCID.GreenSlime,
            NPCID.BlueSlime,
            NPCID.PurpleSlime,
            NPCID.Pinky,
            NPCID.Werewolf
            //Custom Enemy goes here
            );

        public static bool[] UndergroundSC = NPCID.Sets.Factory.CreateNamedSet("UndergroundSeaCreatures").Description("Enemies in this set can be caught when fishing in the Underground Biome").RegisterBoolSet(false,
            NPCID.Mimic,
            NPCID.GiantWormBody,
            NPCID.GiantWormHead,
            NPCID.GiantWormTail,
            NPCID.BlueJellyfish,
            NPCID.DiggerBody,
            NPCID.DiggerHead,
            NPCID.DiggerTail,
            NPCID.ToxicSludge
            );

        public static bool[] CavernSC = NPCID.Sets.Factory.CreateNamedSet("CavernSeaCreatures").Description("Enemies in this set can be caught when fishing in the Cavern Biome").RegisterBoolSet(false,
            NPCID.Mimic,
            NPCID.GiantWormBody,
            NPCID.GiantWormHead,
            NPCID.GiantWormTail,
            NPCID.BlueJellyfish,
            NPCID.GreenJellyfish,
            NPCID.DiggerBody,
            NPCID.DiggerHead,
            NPCID.DiggerTail,
            NPCID.ToxicSludge,
            NPCID.RockGolem,
            NPCID.Salamander,
            NPCID.Salamander2,
            NPCID.Salamander3,
            NPCID.Salamander4,
            NPCID.Salamander5,
            NPCID.Salamander6,
            NPCID.Salamander7,
            NPCID.Salamander8,
            NPCID.Salamander9,
            NPCID.Crawdad,
            NPCID.Crawdad2,
            NPCID.GiantShelly,
            NPCID.GiantShelly2,
            NPCID.Nymph,
            NPCID.Piranha,
            NPCID.AnglerFish
            );

        public static bool[] SnowSC = NPCID.Sets.Factory.CreateNamedSet("SnowSeaCreatures").Description("Enemies in this set can be caught when fishing in the Snow Biome").RegisterBoolSet(false,
            NPCID.IceSlime,
            NPCID.ZombieEskimo,
            NPCID.ArmedZombieEskimo,
            NPCID.IceElemental,
            NPCID.IceGolem,
            NPCID.CorruptPenguin,
            NPCID.CrimsonPenguin
            );

        public static bool[] IceSC = NPCID.Sets.Factory.CreateNamedSet("IceSeaCreatures").Description("Enemies in this set can be caught when fishing in the Ice Underground Biome").RegisterBoolSet(false,
            NPCID.SnowFlinx,
            NPCID.UndeadViking,
            NPCID.ArmoredViking,
            NPCID.IceElemental,
            NPCID.IceTortoise,
            NPCID.IceMimic,
            NPCID.IcyMerman,
            NPCID.PigronCorruption,
            NPCID.PigronCrimson,
            NPCID.PigronHallow
            );

        public static bool[] DesertSC = NPCID.Sets.Factory.CreateNamedSet("DesertSeaCreatures").Description("Enemies in this set can be caught when fishing in the Desert Biome").RegisterBoolSet(false,
            NPCID.Antlion,
            NPCID.SandSlime,
            NPCID.Mummy,
            NPCID.BloodMummy,
            NPCID.DarkMummy,
            NPCID.LightMummy,
            NPCID.SandElemental
            );

        public static bool[] UndergroundDesertSC = NPCID.Sets.Factory.CreateNamedSet("UndergroundDesertSeaCreatures").Description("Enemies in this set can be caught when fishing in the Underground Desert Biome").RegisterBoolSet(false,
            NPCID.DesertDjinn,
            NPCID.DuneSplicerBody,
            NPCID.DuneSplicerHead,
            NPCID.DuneSplicerTail,
            NPCID.TombCrawlerBody,
            NPCID.TombCrawlerHead,
            NPCID.TombCrawlerTail,
            NPCID.FlyingAntlion
            );

        public static bool[] CorruptionSC = NPCID.Sets.Factory.CreateNamedSet("CorruptionSeaCreatures").Description("Enemies in this set can be caught when fishing in the Corruption Biome").RegisterBoolSet(false,
            NPCID.DevourerBody,
            NPCID.DevourerHead,
            NPCID.DevourerTail,
            NPCID.EaterofSouls,
            NPCID.LittleEater,
            NPCID.BigEater,
            NPCID.Corruptor,
            NPCID.Slimer,
            NPCID.Slimer2,
            NPCID.SeekerBody,
            NPCID.SeekerHead,
            NPCID.SeekerTail
            );

        public static bool[] UndergroundCorruptionSC = NPCID.Sets.Factory.CreateNamedSet("UndergroundCorruptionSeaCreatures").Description("Enemies in this set can be caught when fishing in the Underground Corruption Biome").RegisterBoolSet(false,
            NPCID.DevourerBody,
            NPCID.DevourerHead,
            NPCID.DevourerTail,
            NPCID.SeekerBody,
            NPCID.SeekerHead,
            NPCID.SeekerTail,
            NPCID.Corruptor,
            NPCID.CursedHammer,
            NPCID.BigMimicCorruption,
            NPCID.CorruptGoldfish
            );

        public static bool[] CrimsonSC = NPCID.Sets.Factory.CreateNamedSet("CrimsonSeaCreatures").Description("Enemies in this set can be caught when fishing in the Crimson Biome").RegisterBoolSet(false,
            NPCID.Crimera,
            NPCID.BigCrimera,
            NPCID.LittleCrimera,
            NPCID.FaceMonster,
            NPCID.BloodCrawler,
            NPCID.BloodCrawlerWall,
            NPCID.CrimsonGoldfish,
            NPCID.Herpling,
            NPCID.Crimslime
            );

        public static bool[] UndergroundCrimsonSC = NPCID.Sets.Factory.CreateNamedSet("UndergroundCrimsonSeaCreatures").Description("Enemies in this set can be caught when fishing in the Underground Crimson Biome").RegisterBoolSet(false,
            NPCID.FloatyGross,
            NPCID.IchorSticker,
            NPCID.CrimsonAxe,
            NPCID.BigMimicCrimson,
            NPCID.BloodJelly,
            NPCID.BloodFeeder
            );

        public static bool[] JungleSC = NPCID.Sets.Factory.CreateNamedSet("JungleSeaCreatures").Description("Enemies in this set can be caught when fishing in the Jungle Biome").RegisterBoolSet(false,
            NPCID.Piranha,
            NPCID.JungleSlime,
            NPCID.DoctorBones,
            NPCID.AnglerFish,
            NPCID.Derpling,
            NPCID.GiantTortoise,
            NPCID.Arapaima
            );

        public static bool[] UndergroundJungleSC = NPCID.Sets.Factory.CreateNamedSet("UndergroundJungleCreatures").Description("Enemies in this set can be caught when fishing in the Underground Jungle Biome").RegisterBoolSet(false,
            NPCID.JungleCreeper,
            NPCID.JungleCreeperWall,
            NPCID.Hornet,
            NPCID.HornetFatty,
            NPCID.HornetHoney,
            NPCID.HornetLeafy,
            NPCID.HornetSpikey,
            NPCID.HornetStingy,
            NPCID.BigHornetFatty,
            NPCID.BigHornetHoney,
            NPCID.BigHornetLeafy,
            NPCID.BigHornetSpikey,
            NPCID.BigHornetStingy,
            NPCID.BigMossHornet,
            NPCID.GiantMossHornet,
            NPCID.LittleHornetFatty,
            NPCID.LittleHornetHoney,
            NPCID.LittleHornetLeafy,
            NPCID.LittleHornetSpikey,
            NPCID.LittleHornetStingy,
            NPCID.LittleMossHornet,
            NPCID.MossHornet,
            NPCID.Piranha,
            NPCID.Arapaima,
            NPCID.GiantTortoise,
            NPCID.Moth,
            NPCID.LacBeetle
            );

        public static bool[] DungeonSC = NPCID.Sets.Factory.CreateNamedSet("DungeonSeaCreatures").Description("Enemies in this set can be caught when fishing in the Dungeon").RegisterBoolSet(false,
            NPCID.AngryBones,
            NPCID.AngryBonesBig,
            NPCID.AngryBonesBigHelmet,
            NPCID.AngryBonesBigMuscle,
            NPCID.CursedSkull,
            NPCID.DungeonSlime,
            NPCID.DungeonSpirit
            //Custom Enemy goes here
            );

        public static bool[] OceanSC = NPCID.Sets.Factory.CreateNamedSet("OceanSeaCreatures").Description("Enemies in this set can be caught when fishing in the Ocean").RegisterBoolSet(false,
            NPCID.PinkJellyfish,
            NPCID.Crab,
            NPCID.Squid,
            NPCID.Shark,
            NPCID.SeaSnail
            );

        public static bool[] LavaSC = NPCID.Sets.Factory.CreateNamedSet("LavaSeaCreatures").Description("Enemies in this set can be caught when fishing in Lava").RegisterBoolSet(false,
            NPCID.BlueArmoredBones,
            NPCID.BlueArmoredBonesMace,
            NPCID.BlueArmoredBonesNoPants,
            NPCID.BlueArmoredBonesSword,
            NPCID.RustyArmoredBonesAxe,
            NPCID.RustyArmoredBonesFlail,
            NPCID.RustyArmoredBonesSword,
            NPCID.RustyArmoredBonesSwordNoArmor,
            NPCID.HellArmoredBones,
            NPCID.HellArmoredBonesMace,
            NPCID.HellArmoredBonesSpikeShield,
            NPCID.HellArmoredBonesSword,
            NPCID.Demon,
            NPCID.Mimic,
            NPCID.LavaSlime,
            NPCID.Hellbat,
            NPCID.BoneSerpentBody,
            NPCID.BoneSerpentHead,
            NPCID.BoneSerpentTail,
            NPCID.Lavabat,
            NPCID.RedDevil
            );

        public static bool[] AllSC = NPCID.Sets.Factory.CreateNamedSet("AllSeaCreatures").Description("Set of all Sea Creatures").RegisterBoolSet(false,
            //Lava SC
            NPCID.BlueArmoredBones,
            NPCID.BlueArmoredBonesMace,
            NPCID.BlueArmoredBonesNoPants,
            NPCID.BlueArmoredBonesSword,
            NPCID.RustyArmoredBonesAxe,
            NPCID.RustyArmoredBonesFlail,
            NPCID.RustyArmoredBonesSword,
            NPCID.RustyArmoredBonesSwordNoArmor,
            NPCID.HellArmoredBones,
            NPCID.HellArmoredBonesMace,
            NPCID.HellArmoredBonesSpikeShield,
            NPCID.HellArmoredBonesSword,
            NPCID.Demon,
            NPCID.Mimic,
            NPCID.LavaSlime,
            NPCID.Hellbat,
            NPCID.BoneSerpentBody,
            NPCID.BoneSerpentHead,
            NPCID.BoneSerpentTail,
            NPCID.Lavabat,
            NPCID.RedDevil,
            //Ocean SC
            NPCID.PinkJellyfish,
            NPCID.Crab,
            NPCID.Squid,
            NPCID.Shark,
            NPCID.SeaSnail,
            //Dungeon SC
            NPCID.AngryBones,
            NPCID.AngryBonesBig,
            NPCID.AngryBonesBigHelmet,
            NPCID.AngryBonesBigMuscle,
            NPCID.CursedSkull,
            NPCID.DungeonSlime,
            NPCID.DungeonSpirit,
            //Custom Dungeon Enemy
            //Jungle SC
            NPCID.JungleCreeper,
            NPCID.JungleCreeperWall,
            NPCID.Hornet,
            NPCID.HornetFatty,
            NPCID.HornetHoney,
            NPCID.HornetLeafy,
            NPCID.HornetSpikey,
            NPCID.HornetStingy,
            NPCID.BigHornetFatty,
            NPCID.BigHornetHoney,
            NPCID.BigHornetLeafy,
            NPCID.BigHornetSpikey,
            NPCID.BigHornetStingy,
            NPCID.BigMossHornet,
            NPCID.GiantMossHornet,
            NPCID.LittleHornetFatty,
            NPCID.LittleHornetHoney,
            NPCID.LittleHornetLeafy,
            NPCID.LittleHornetSpikey,
            NPCID.LittleHornetStingy,
            NPCID.LittleMossHornet,
            NPCID.MossHornet,
            NPCID.Piranha,
            NPCID.Arapaima,
            NPCID.GiantTortoise,
            NPCID.Moth,
            NPCID.LacBeetle,
            NPCID.JungleSlime,
            NPCID.DoctorBones,
            NPCID.AnglerFish,
            NPCID.Derpling,
            //Crimson SC
            NPCID.FloatyGross,
            NPCID.IchorSticker,
            NPCID.CrimsonAxe,
            NPCID.BigMimicCrimson,
            NPCID.BloodJelly,
            NPCID.BloodFeeder,
            NPCID.Crimera,
            NPCID.BigCrimera,
            NPCID.LittleCrimera,
            NPCID.FaceMonster,
            NPCID.BloodCrawler,
            NPCID.BloodCrawlerWall,
            NPCID.CrimsonGoldfish,
            NPCID.Herpling,
            NPCID.Crimslime,
            //Corruption
            NPCID.DevourerBody,
            NPCID.DevourerHead,
            NPCID.DevourerTail,
            NPCID.SeekerBody,
            NPCID.SeekerHead,
            NPCID.SeekerTail,
            NPCID.Corruptor,
            NPCID.CursedHammer,
            NPCID.BigMimicCorruption,
            NPCID.CorruptGoldfish,
            NPCID.EaterofSouls,
            NPCID.LittleEater,
            NPCID.BigEater,
            NPCID.Slimer,
            NPCID.Slimer2,
            //Desert SC
            NPCID.DesertDjinn,
            NPCID.DuneSplicerBody,
            NPCID.DuneSplicerHead,
            NPCID.DuneSplicerTail,
            NPCID.TombCrawlerBody,
            NPCID.TombCrawlerHead,
            NPCID.TombCrawlerTail,
            NPCID.Antlion,
            NPCID.SandSlime,
            NPCID.Mummy,
            NPCID.BloodMummy,
            NPCID.DarkMummy,
            NPCID.LightMummy,
            NPCID.SandElemental,
            NPCID.FlyingAntlion,
            //Snow and Ice SC
            NPCID.SnowFlinx,
            NPCID.UndeadViking,
            NPCID.ArmoredViking,
            NPCID.IceElemental,
            NPCID.IceTortoise,
            NPCID.IceMimic,
            NPCID.IcyMerman,
            NPCID.PigronCorruption,
            NPCID.PigronCrimson,
            NPCID.PigronHallow,
            NPCID.IceSlime,
            NPCID.ZombieEskimo,
            NPCID.ArmedZombieEskimo,
            NPCID.IceGolem,
            NPCID.CorruptPenguin,
            NPCID.CrimsonPenguin,
            //Underground and Cavern SC
            NPCID.GiantWormBody,
            NPCID.GiantWormHead,
            NPCID.GiantWormTail,
            NPCID.BlueJellyfish,
            NPCID.GreenJellyfish,
            NPCID.DiggerBody,
            NPCID.DiggerHead,
            NPCID.DiggerTail,
            NPCID.ToxicSludge,
            NPCID.RockGolem,
            NPCID.Salamander,
            NPCID.Salamander2,
            NPCID.Salamander3,
            NPCID.Salamander4,
            NPCID.Salamander5,
            NPCID.Salamander6,
            NPCID.Salamander7,
            NPCID.Salamander8,
            NPCID.Salamander9,
            NPCID.Crawdad,
            NPCID.Crawdad2,
            NPCID.GiantShelly,
            NPCID.GiantShelly2,
            NPCID.Nymph,
            //Forest SC
            NPCID.Zombie,
            NPCID.DemonEye,
            NPCID.GreenSlime,
            NPCID.BlueSlime,
            NPCID.PurpleSlime,
            NPCID.Pinky,
            NPCID.Werewolf,
            //Custom Forest Enemy
            //Space SC
            NPCID.WyvernHead,
            NPCID.WyvernBody,
            NPCID.WyvernBody2,
            NPCID.WyvernBody3,
            NPCID.WyvernTail,
            NPCID.WyvernLegs,
            NPCID.FlyingFish
            //Custom Space Enemy
            );

        public static bool[] GoldCritters = ItemID.Sets.Factory.CreateNamedSet("AllGoldenCritters").Description("Set of all Golden Critters").RegisterBoolSet(false,
            ItemID.GoldBird,
            ItemID.GoldBunny,
            ItemID.GoldButterfly,
            ItemID.GoldDragonfly,
            ItemID.GoldFrog,
            ItemID.GoldGoldfish,
            ItemID.GoldGrasshopper,
            ItemID.GoldLadyBug,
            ItemID.GoldMouse,
            ItemID.GoldSeahorse,
            ItemID.SquirrelGold,
            ItemID.GoldWaterStrider,
            ItemID.GoldWorm
            );
    }
}